### ISSUE TITLE
mysql-connector-python==2.0.4 is available (you have 2.1.3)

### ISSUE THREAD

**Issue by ElMoribond** [jgonggrijp/pip-review#10]
Hello

Today I use pip-review for first time.
I updated several packets successfully. Thanks to dev :)
But it remains a wonder that dilemma (I am under ARM Archlinux).
$ pip-review
mysql-connector-python==2.0.4 is available (you have 2.1.3)

It's normal?

**Comment by jgonggrijp** [comment]
No, that's not supposed to happen. Thanks for reporting this. I will accept pull requests that fix this, otherwise the fix is probably going to happen after I find the time to rewrite `pip-review` to use `pip list --outdated`.

**Comment by jgonggrijp** [comment]
I just found out that this issue appears to have been reported before to the original pip-tools repo. That ticket contained more examples.

https://github.com/nvie/pip-tools/issues/123

**Comment by lardconcepts** [comment]
More examples

```
distro-info==0.10 is available (you have =0.14build1)
pygobject==2.28.3 is available (you have 3.22.0)
python-apt==0.7.8 is available (you have 1.1.0b5)


prettytable==7 is available (you have 0.7.2)
Upgrade now? [Y]es, [N]o, [A]ll, [Q]uit Y
Collecting prettytable==7
  Could not find a version that satisfies the requirement prettytable==7 (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2)
No matching distribution found for prettytable==7
```

**Comment by jgonggrijp** [comment]
@ElMoribond @lardconcepts @k4rtik can you please try the current version from develop on the system on which you experienced this issue? It should be fixed thanks to the patch by bil-elmoussaoui.

**Comment by k4rtik** [comment]
That's great news, I have not seen the issue appear in last couple of weeks. However, is the following expected behavior?

```
$ pip-review -i
Everything up-to-date
$ pip list -o
setuptools (32.3.0) - Latest: 33.1.0 [wheel]
$ pip-review -i
Everything up-to-date
```

**Comment by jgonggrijp** [comment]
Well that is "expected", in the sense that it is a known but unrelated problem: #13.

**Comment by k4rtik** [comment]
@jgonggrijp as long as that is also expected on macOS, I am okay with it. 😄
