### ISSUE TITLE
New feature: Install from the Unofficial Windows Binaries for Python Extension Packages

### ISSUE THREAD

**Issue by someparsa** [jgonggrijp/pip-review#102]
I have seen that many users have difficulty using the standard PIP repo. Maybe the binaries are corrupt or their system needs the wheel files shared on the link below. I suggest we add a new feature to give the users the opportunity to download from this repository too. This is the code I have developed but we can polish it to be more user-friendly. I have not seen any other package giving such opportunity to the users.

I tried to make system recognitions automatic and the user won't struggle opening a browser, download the wheel file, go to the terminal, etc. Everything with just a line of command is in their hands. Maybe a command like:

> [Archived: Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/)
> by [Christoph Gohlke](https://www.cgohlke.com/). Updated on 26 June 2022 at 07:27 UTC.

I tried to make system recognitions automatic and the user won't struggle opening a browser, download the wheel file, go to the terminal, etc. Everything with just a line of command is in their hands. Maybe a command like:

**`pip-review upep <- package-name -> <- package-version ->`**

If we like the feature, we may be able to make a mirror to the original link and make the 'pip-review' a semi-pip package.

```
def uPEP (pckg_name, pckg_version):

    '''
    Function to download Unofficial Windows Binaries for Python. Developer is not affiliated with the UCI, is not in any contract of any type with the developers of the following page, and is not maintainer of the packages presented in the link below.

    You may use this package and links downloaded at your own risk. There is no guarantee that the links work properly, or the files downloaed do not harm your system.

    Archived: Unofficial Windows Binaries for Python Extension Packages
    by Christoph Gohlke. Updated on 26 June 2022 at 07:27 UTC.
    '''

    webPath = "https://download.lfd.uci.edu/pythonlibs/archived/"
    webView = "https://www.lfd.uci.edu/~gohlke/pythonlibs/"

    import sys

    cpu_arch = ""
    for i in range (-7,-2):
        cpu_arch = cpu_arch + sys.version[i]

    if "32" in cpu_arch:
        cpu_mch = "win32"
    else:
        cpu_mch = "win_amd64"

    pthn_version = str(sys.version_info.major) + str(sys.version_info.minor)

    if sys.version_info.minor <=7:
        pthn_release = "cp" + pthn_version + "-cp" + pthn_version + "m"
        webAddress = webPath + "cp" + pthn_version + "/"

    else:
        pthn_release = "cp" + pthn_version + "-cp" + pthn_version
        webAddress = webPath + pthn_version + "/"

    webFile = pckg_name + "-" + pckg_version + "-" + pthn_release + "-" + cpu_mch + ".whl"

    import requests

    r = requests.get(webView)

    if webFile or re.sub("-", u"\u2013", webFile) in r.text:
        print ('Yes')
    else:
        print ('No')
    
    return webFile

input("Do you want to install the package?" )

if input == 'Y':

    import os
    os.system("python -m pip install "+ uPEP("xgboost", "1.6.1"))

else:

    print("Quit!")
```

**Comment by jgonggrijp** [comment]
How to install packages and from where is a responsibility that we defer to `pip`. Would `pip`'s built-in options `--index-url`, `--extra-index-url` or `--find-links` not already do the job here? Run `pip help install` for documentation, section "Package Index Options".

**Comment by someparsa** [comment]
This is what we read in the help:

> **-i, --index-url <url>**
> Base URL of the Python Package Index (default https://pypi.org/simple). This should point to a repository compliant with PEP 503 (the simple repository API) or a local directory laid out in the same format.

Then the normal syntax will be something like this, without the freedom to call other options like the version or the architecture of the system.

`python -m pip install -f 'https://download.lfd.uci.edu/pythonlibs/archived/'`**` <- package ->`**

I think the existing feature in pip does not have all the freedom we can add with the proposed feature.

**Comment by jgonggrijp** [comment]
**`<- package ->`** may include the version number, like so: `pip-review==1.3.0`. I think the architecture can be set with other flags.

`pip-review` forwards all arguments it doesn't recognize to `pip`, so if you call something like `pip-review --auto --extra-index-url 'https://download.lfd.uci.edu/pythonlibs/archived/'`, that will update packages from that unofficial Windows respository, in addition to PyPI.

If you are proposing to not only review updates, but also install new packages, then I say: let's not widen the scope of pip-review. Installing new packages is the business of `pip`. If `pip` is lacking in some way, contribute to `pip` instead!

**Comment by someparsa** [comment]
Agreed Julian, you are right. We are making an interface for easier usage of the PIP. So I will mark this ticket for closure.
