### ISSUE TITLE
pip list --outdated found outdated packages but pip-review didn't

### ISSUE THREAD

**Issue by dattienle2573** [jgonggrijp/pip-review#108]
<img width="290" alt="image" src="https://github.com/jgonggrijp/pip-review/assets/140530253/e202a242-a670-4c99-8b71-1506e94dc1f1">

**Comment by jgonggrijp** [comment]
What is the output of `pip-review --help`?

**Comment by jgonggrijp** [comment]
@dattienle2573 why did you close the issue?
