### ISSUE TITLE
Also install as a module so "python3.4 -m pip-review" will work

### ISSUE THREAD

**Issue by Femtometer** [jgonggrijp/pip-review#11]
Console says “No module named pip-review”.
Installed log:
```
python3.4 -m pip install pip-review
Collecting pip-review  
  Using cached pip-review-0.4.tar.gz  
Installing collected packages: pip-review  
  Running setup.py install for pip-review ... done  
Successfully installed pip-review-0.4  
```

**Comment by jgonggrijp** [comment]
(I edited your post for better formatting. Use triple backticks to format multiline code. Thank you.)

Python 3 is still unsupported, unfortunately. However, it is on my wish list.

**Comment by Femtometer** [comment]
```
$ which pip-review
/Library/Frameworks/Python.framework/Versions/3.4/bin/pip-review
Mar:2.7 Tension$ python2 -m pip list    
gfwlist2pac (1.1.3)    
pip (8.1.2)    
pip-review (0.4)    
setuptools (20.9.0)    
$ python2 -m pip-review    
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip-review    
$ pip2 --version    
pip 8.1.2 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)
```
I have multi-version python installed. I can't use pip-review like pip with "pythonx.x -m package-name".
It can be a package which can be executed.

**Comment by jgonggrijp** [comment]
Ah, that is clarifying. So ideally `pip-review` should not only be installed as a script but also as a module. I'll update the ticket title to make this clear.

**Comment by jgonggrijp** [comment]
As of [version 0.5](https://pypi.python.org/pypi/pip-review/0.5), pip-review is also installed as a module under the name `pip_review` (note the underscore instead of the dash).
