### ISSUE TITLE
Passing --break-system-packages to pip-review

### ISSUE THREAD

**Issue by aakhmetz** [jgonggrijp/pip-review#112]
Hello, I wonder if it would be possible to pass some additional argurment to pip-review command, which will be passed to each `pip` internally.

It is because now I need to pass an argument `--break-system-packages` for each `pip install` command. Is it possible to pass it while invoking pip-review?

Specifically, running `pip-review --local --auto` gives me a message from `pip`:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
which means that I need to write `pip install xyz --break-system-packages` instead of simply `pip install xyz`

Thank you for taking a look in advance!

**Comment by jgonggrijp** [comment]
If I'm not mistaken, `pip-review` already forwards all arguments it doesn't know to `pip list` and `pip install`. So if you do `pip-review --local --auto --break-system-packages`, that *might* already do what you want.

If that gives you an error, it means that `pip list` does not accept the `--break-system-packages` option. `pip-review` has internal lists of arguments that should be passed to `pip list` but not to `pip install` and vice versa. You *could* get `--break-system-packages` to work by adding it to the list for `pip install` only options. I would accept a pull request that makes that change.

That being said, I think the message you're getting from `pip` contains a lot of wisdom. Packages that ship with your distro will be updated without you needing to run `pip-review`. I can also tell you from personal experience that `pipx` is very convenient. I would recommend both options over `pip-review --auto --break-system-packages` without a doubt.

**Comment by aakhmetz** [comment]
Dear @jgonggrijp 

Thank you for your detailed response and your opinion. I've played with pipx a bit and I like it. So maybe, no need to do a pull request. On the other side, I had used ```pip-review``` for quite a while and it was convenient, so many thanks for your work!
