### ISSUE TITLE
Travis builds are failing while pip-review actually works

### ISSUE THREAD

**Issue by jgonggrijp** [jgonggrijp/pip-review#15]
If you find a way to repair the tests, please submit a pull request!

**Comment by xoviat** [comment]
Is there a particular reason that Python26 is still supported?

**Comment by jgonggrijp** [comment]
No, except that it still appears to work. As long as it works without additional effort, I intend to support it. But given that choice, I believe some work to repair the test is justified.

**Comment by jgonggrijp** [comment]
cElementTree is in the tests because of `## FIXME:` output in `pip freeze` (see nvie#9). When #32 is resolved, we won't be using `pip freeze` anymore, so cElementTree can be removed from the tests. That will remove the barrier to including Python 3 in the Travis build. Credits to @Flimm for research.
