### ISSUE TITLE
Printing uncorrectly package names

### ISSUE THREAD

**Issue by brupelo** [jgonggrijp/pip-review#17]
For some reason on python3.5.1 win7 the first letters of the packages (when asking if i want to upgrade or not) are wrong, you can see what i mean on this [screen](https://dl.dropboxusercontent.com/u/21334722/Uploads/2016/12/2016-12-02_14-26-18.png)

**Comment by jgonggrijp** [comment]
Yes, this is a known issue (#14). It was fixed in #16, but I haven't published a new version that includes the fix yet.

**Comment by brupelo** [comment]
Cool, thanks, looking forward for the new release ;)
