### ISSUE TITLE
Crashes with pip < 6.x

### ISSUE THREAD

**Issue by Gillingham** [jgonggrijp/pip-review#2]
```pip-review
Traceback (most recent call last):
  File "/virtualenv/bin/pip-review", line 40, in <module>
    from pip._vendor.packaging import version as packaging_version
ImportError: No module named packaging
```
```
pip (1.5.4)
pip-review (0.4)
```

Using pip-tools==0.3.6 pip-review works fine with the same old version of pip so it looks like there was a regression after the fork.

**Comment by jgonggrijp** [comment]
Yes that's right, this dependency was introduced with pull request #1. The `--pre` flag depends on it. I didn't realise this could break things for people using old versions of pip, sorry for not thinking that through. Is upgrading pip not an option for you?

**Comment by Gillingham** [comment]
I can upgrade, just wanted to report this as it is a bit of a regression and pip 1.5.4 is what comes stock on Ubuntu 14.04 LTS so I'm sure people will be running into this.
I guess its up to you if you want to just update install_requires in setup.py to depend on pip>=6 or figure out a work-around, for me I do all development from virtualenvs so updating pip is never an issue.

**Comment by jgonggrijp** [comment]
Thanks for reporting. I can probably make it work without depending on pip>=6, so I'll fix it that way.
