### ISSUE TITLE
pip-review does not compare versions correctly 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jgonggrijp/pip-review#30]
I'm using pip-review with python3.6 on Linux
As you can see here what i got by runing `sudo pip-review --interactive`
`isc==0.0.0 is available (you have 2.0)`
`louis==1.3 is available (you have 3.0.0)`
`python-sane==2.8.2 is available (you have 2.8.3)`
`pygobject==2.28.3 is available (you have 3.22.0)`

I can push a fix if you wish ;)

**Comment by jgonggrijp** [comment]
Please do. Note that this is a duplicate of #10; please refer to that issue in your pull request.
