### ISSUE TITLE
Reimplement pip-review on top of pip list --outdated

### ISSUE THREAD

**Issue by jgonggrijp** [jgonggrijp/pip-review#32]
Instead of using `pip freeze` to get a list of installed packages and then running custom code to fetch the latest version from pypi.python.org, simply call `pip list --outdated` to get all the necessary information at once. Forward arguments like `--pre`, `--local` and `--user` directly to the call to `pip list --outdated`.

Will allow us to replace the `load_pkg_info`, `guess_pkg_name`, `get_pkg_info`, `latest_version`, `get_latest_versions` and `get_installed_pkgs` by a single short function that does the call to `pip list --outdated`.

Will resolve #6, #18, #21 and #27 at once.

After this change, pip-review will formally depend on pip>=1.3. This is the first version of pip that shipped with the `list` subcommand and the corresponding `--outdated` option.

**Comment by bil-elmoussaoui** [comment]
I've fixed #32 #6 #18  and #21, should i open separate PR or just one is enough ?
It need some testing :)

**Comment by jgonggrijp** [comment]
That's great! I think one pull request is sufficient, because (I believe) all these issues are tightly coupled.

Please be prepared for some review rounds before it gets accepted. This is something I want to get right from the first moment and I happen to be opinionated on the matter. I should emphasize that I'm glad you took up on this, though. ;-)

**Comment by jgonggrijp** [comment]
Updated the title and the opening post because of #41.

**Comment by xoviat** [comment]
Not going to do this myself, but this should be trivial with the `--format` option:

```
pip list --outdated --format=freeze
```

**Comment by xoviat** [comment]
And then I read the PR and find out that `--format` is too new.

**Comment by jgonggrijp** [comment]
It's complicated.

**Comment by jgonggrijp** [comment]
New related PR: #53.

**Comment by jgonggrijp** [comment]
Closed in [version 1.0](https://github.com/jgonggrijp/pip-review/releases/tag/1.0).
