### ISSUE TITLE
Look out for a more robust testing framework

### ISSUE THREAD

**Issue by jgonggrijp** [jgonggrijp/pip-review#39]
I'm not a great fan of `cram`. It works, but it forces us to write workarounds (see #37). If you can think of a better solution, please let me know.

**Comment by xoviat** [comment]
py.test seems to be the bandwagon these days. In addition, some people (not me personally) like to wrap it with tox.

**Comment by jgonggrijp** [comment]
I love py.test, but it is meant for unit tests. I think it is a good idea to add unit tests (with py.test), but those do not replace wholesale functional tests, which is what cram currently provides.

**Comment by xoviat** [comment]
PyInstaller has [extensive functional testing][1] all based on py.test.

[1]: https://travis-ci.org/pyinstaller/pyinstaller/jobs/198403202

**Comment by jgonggrijp** [comment]
Thanks, I'll study that.

**Comment by jgonggrijp** [comment]
Closing this as I consider it an archived discussion.
