### ISSUE TITLE
Use subprocess.call([sys.executable, '-m', 'pip', ...]) to call pip

### ISSUE THREAD

**Issue by sth4nothing** [jgonggrijp/pip-review#44]
Do **not** use "`os.system('pip install {0}=={1}'.format(pkg, version))`".

Instead, I suggest doing as follows:
```python
import pip
pip.main(['install', '{0}=={1}'.format(pkg, version)])
```

Sorry for my poor English.

**Comment by sth4nothing** [comment]
And so, check for updates : `pip.main(['list', '-o'])`

**Comment by jgonggrijp** [comment]
@sth4nothing Please explain what you mean by "cannot work well with multiple versions of Python". What problems may arise in our current use of `os.system`? How does `pip.main` solve that?

Regarding the use of `pip list -o`: this is already work in progress. See #32 and #41.

**Comment by sth4nothing** [comment]
@jgonggrijp if both python3.5 and python3.4 are installed, the problem will be triggered. And use `pip.main()` can avoid this.

**Comment by jgonggrijp** [comment]
@sth4nothing *What problem* will be triggered if both Python 3.5 and Python 3.4 are installed?

**Comment by sth4nothing** [comment]
@jgonggrijp Sorry for my unclear description. Suppose that one has install 3.4 & 3.5 or other versions, and the default `pip` command is the pip of python3.5, when he wants to update packages of python3.4, things will go wrong.

**Comment by jgonggrijp** [comment]
Would it not make more sense to use separate virtual environments in such a case? See http://docs.python-guide.org/en/latest/dev/virtualenvs/ .

I'm hesitant to depend on `pip` internals, because they do not have any policy in place to promise any feature stability. In other words, they do not offer a supported API.

**Comment by xoviat** [comment]
Actually, what you're supposed to do is this:

```
import subprocess
import sys
subprocess.call([sys.executable, '-m', 'pip', 'install', '{0}=={1}'.format(pkg, version)])
```

**Comment by sth4nothing** [comment]
@xoviat wow, thanks!

**Comment by jgonggrijp** [comment]
Yes, that looks like the best of both worlds. I welcome pull requests that implement what @xoviat suggested.

**Comment by jgonggrijp** [comment]
Closed in #45. The change will be included with the 1.0 release.

**Comment by derrick-gopher** [comment]
Here is how i used sub-process for multiple arguments with pip.
```
pkg =<package to install>
subprocess.call([sys.executable,'-m', 'pip', 'install','--trusted-host=pypi.org', '--trusted-host=files.pythonhosted.org', pkg])
```

**Comment by jgonggrijp** [comment]
Thanks @derrick-gopher. I think what you're describing is essentially the same as in https://github.com/jgonggrijp/pip-review/issues/44#issuecomment-277720359 (a few comments up). This is also what is being used in pip-review 1.x.

**Comment by derrick-gopher** [comment]
welcome, I commented because i could not find a proper example of adding pip options.
my challenge is that am using a company proxy,so i needed the extra options.
