### ISSUE TITLE
How to use pip-review for various Python versions?

### ISSUE THREAD

**Issue by sbibauw** [jgonggrijp/pip-review#46]
I have both Python 2.7 and 3.6 installed (by Homebrew). When running `pip-review`, it only tries to update `python2.7/site-packages/` (as would `pip` or `pip2` list them).

Is there a way to force `pip-review` to update Python 3 packages? A kind of `pip-review3` or `pip-review --python3`? (I have looked at `--help` and issues here but haven't found a solution...)

**Comment by jgonggrijp** [comment]
Does `python3 -m pip_review` work for you?

**Comment by sbibauw** [comment]
@jgonggrijp It works, but does the exact same as `pip-review` (only updates python2.7 dependencies), even though it is installed as a python3.6 package...

**Comment by jgonggrijp** [comment]
Oh, I understand. I believed this was already fixed because of #44. However, that pull request hasn't been merged yet. Which is my fault. I will try to bring out a new release asap.

In the meanwhile, your best option is probably to use a virtualenv.

**Comment by sbibauw** [comment]
Great, thank you!
