### ISSUE TITLE
Document that selfupdate requires call by `python -m pip_review`

### ISSUE THREAD

**Issue by xoviat** [jgonggrijp/pip-review#47]
this problem happens for the same reason that pip needs to be upgraded with `python -m upgrade pip`. solutions for this are the following:

- don't allow pip-review to upgrade itself
- start a daemon process that waits until the parent has exited, then run the upgrade

@jgonggrijp what do you think?

**Comment by jgonggrijp** [comment]
I'm hoping to merge and release #44 soon. Would that solve this issue? I would like to avoid both options in your bullet list, if possible.

**Comment by xoviat** [comment]
No. This problem is specifically caused by entry_points (which I believe I added). The machinery that calls the function that you defined opens file locks that aren't returned until the entry point function returns. When pip is called, it notices those file locks and aborts.

**Comment by jgonggrijp** [comment]
If `entry_points` is the problem, then the entire problem can be avoided by calling `python -m pip_review` instead of the generated `pip-review` executable. Right?

FWIW, I implemented the `entry_points` solution.

**Comment by xoviat** [comment]
> If entry_points is the problem, then the entire problem can be avoided by calling python -m pip_review instead of the generated pip-review executable. Right?

Correct.
