### ISSUE TITLE
setuptools-specific features in setup.py break Travis build

### ISSUE THREAD

**Issue by jgonggrijp** [jgonggrijp/pip-review#48]
In the latest release branch, I converted `setup.py` to use the proper notation for supported Python versions (ccf48c30) and platform-specific dependencies (47203ee3). Unfortunately, that [broke the Travis build](https://travis-ci.org/jgonggrijp/pip-review/builds/220136344). For some unclear reason that I need help with, these features cause the installation step to fail at `pip install .`. I do not see these errors if I run the tests locally with `tox`.

I tried updating pip (a29db746), but that [didn't help](https://travis-ci.org/jgonggrijp/pip-review/builds/220140481). I also tried ensuring that setuptools is installed (6e428696), but that [didn't make a difference](https://travis-ci.org/jgonggrijp/pip-review/builds/220142953), either. I decided to accept the broken Travis builds for now and release anyway ([0.5.3](https://github.com/jgonggrijp/pip-review/releases/tag/0.5.3)), because I felt reasonably certain that `pip-review` still installs and works, but the problem is unsolved.

If somebody knows how to solve this, help will be much appreciated.

**Comment by xoviat** [comment]
@jgonggrijp Fixed
