### ISSUE TITLE
tries to upgrade ipython to 6.0 on Python 2, which is impossible and never will be possible

### ISSUE THREAD

**Issue by JulesGM** [jgonggrijp/pip-review#52]
Hello Guys,
`pip-preview` currently tries to upgrade Python 2  's ipython to 6.0, even though it's not available on python 2, and never will, as the jupyter/ipython devs have come out clearly saying they will never support python 2 on 6 and onwards.
 `pip list --outdated` accurately doesn't show ipython 6.0 for Python 2.

**Comment by jgonggrijp** [comment]
Thanks for reporting this. This will be fixed with #41.

**Comment by jgonggrijp** [comment]
Fixed in [version 1.0](https://github.com/jgonggrijp/pip-review/releases/tag/1.0).
