### ISSUE TITLE
Add a LICENSE.txt

### ISSUE THREAD

**Issue by jgonggrijp** [jgonggrijp/pip-review#56]
The project is documented as being distributed under the BSD license. This is intended (both by Vincent Driessen and by myself), but no license file is included. This [appears to be necessary](https://packaging.python.org/tutorials/distributing-packages/#license-txt). So I'll add it sometime soon.

**Comment by jgonggrijp** [comment]
@nvie Is it OK with you if I add the [3-clause BSD license text](https://opensource.org/licenses/BSD-3-Clause) to the pip-review repository with the following header?

    Copyright 2012-2015 Vincent Driessen
    Copyright 2015-2017 Julian Gonggrijp

**Comment by nvie** [comment]
> @nvie Is it OK with you if I add the 3-clause BSD license text to the pip-review repository with the following header?

Completely fine by me 👍

**Comment by jgonggrijp** [comment]
Thanks, cheers!
