### ISSUE TITLE
pip-review also updates pip, maybe mention that in the Readme

### ISSUE THREAD

**Issue by ABruihler** [jgonggrijp/pip-review#59]
Quick question that I'm not knowledgable enough to figure out the answer myself and haven't been able to find out through searching - does pip-review update pip itself, or not?  Also, would this be good to mention in the README, or is it just something that's obvious to everyone except me?

**Comment by jgonggrijp** [comment]
As of version 1.0, `pip-review` is a thin wrapper around `pip`. The status as a wrapper is documented, both in the Readme and in `pip-review -h`. Pip does update itself, so yes, pip-review will update pip. Basically, neither pip nor pip-review will make an exception for any package. Do you believe that belongs in the Readme?

**Comment by ABruihler** [comment]
Thanks!  I guess that somehow I hadn't made that connection and hadn't checked to see if `pip` updates itself.  I do think that it would be helpful for some to include this in the Readme, perhaps in something like a FAQ at the bottom, or by change the example to include upgrading `pip`?  On the other hand, I suppose it is something that should be pretty apparent (especially with an issue about it now), and possibly not worth the space in the README.
