### ISSUE TITLE
Pass --ignore-installed  and other flags to pip install

### ISSUE THREAD

**Issue by petobens** [jgonggrijp/pip-review#62]
Is there a way to pass the `--ignore-installed` flag? If there isn't can you add the feature? Thanks!

**Comment by petobens** [comment]
Ok. Will set the option through the pip config file in the mean time. Thanks for the quick reply.

**Comment by jgonggrijp** [comment]
I think I want to go for a compromise: hardcode a set of options that is recognized by `pip list` but not by `pip install` and vice versa. Pass those options only to the respective `pip` command. Pass all other unrecognized options to both.

This approach would mostly fix bugs, especially with the `--user` flag, but it may also cause unexpected behaviour in some cases. Technically, it is a breaking change. Opinions welcome: should I leave this for the 2.0 release, or could it be in a 1.x release?

**Comment by dimitry-ishenko** [comment]
I vote for fix in version 1.x

**Comment by bobzomer** [comment]
To avoid breaking change, we could add two new specific options:
- --install_only_parameters: All the parameters after this will be sent to install only
- --common_parameters: All the parameters after this will be sent to both list and install
Without these parameters, the unknown parameters are sent to list only => we keep a full backward compatibility.

**Comment by jgonggrijp** [comment]
@bobzomer Clever! But isn't that a bit long-winded? If somebody is using the `--user` flag, they'll have to choose between two evils:

- `pip-review -i --user`, which is broken, or
- `pip-review -i --common_parameters --user`, which is rather long to type.

I imagine such users would happily accept a little bit of breaking change so they can have a short command that works correctly.

**Comment by tan-wei** [comment]
Waiting for the update which makes `--user` more useful.

**Comment by jgonggrijp** [comment]
@tan-wei @bobzomer @petobens @joshbode @mihaic @HaleTom @x-ji @cjbassi @dimitry-ishenko @Konfekt This should be solved in version 1.1.0. Please install the update and report back here if there is still something not working.

Also, I'm looking for somebody to take over. See #76.

**Comment by tan-wei** [comment]
Thanks. I can confirm it works well on Manjaro now.
