### ISSUE TITLE
pip-review tries to update packages installed with `--user` at a root level

### ISSUE THREAD

**Issue by cjbassi** [jgonggrijp/pip-review#68]
I'm trying to update packages installed with `pip install --user` so I ran `pip-review --user --auto` which correctly detects the right user level packages to upgrade, but then tries to install them globally to `/usr/lib/python3.7/site-packages/...`.

**Comment by jgonggrijp** [comment]
Yes, this is a known issue. Please refer to #6 (closed) and #62 (open) for more information.

Until this is fixed, you can avoid the problem by using a virtualenv.
