### ISSUE TITLE
match available upgrade to compatibility with latest version of main tool?

### ISSUE THREAD

**Issue by MalikRumi** [jgonggrijp/pip-review#7]
First, I think this is a great tool, thanks for rescuing it. My question arises as I look at upgrading to Django 1.9.1 from 1.7. Pip-review does not tell me if any of my dependencies, new or not, are compatible with Django 1.9.1. I'm thinking something like:

dependency x, new version, is compatible with Django x, latest version (or any other Python app)

I don't know if this is possible, or how difficult it would be to implement, but it sure would be a nice convenience. Call it a feature request more than an 'issue'. Let me know what you think, Thx.

**Comment by MalikRumi** [comment]
I just noticed that if I have an outdated dependency that has no new version, pip-review will not pick that up (e.g., django-postgrespool). Maybe you already knew that, but I thought I'd mention it since I've already added to your issues list

**Comment by jgonggrijp** [comment]
Regarding your first post: could you clarify your feature request a bit, perhaps with some mock output as a full example?

Regarding your second post: is it at all related to your first post? If so, how? If not, could you please file a separate ticket for it?

**Comment by jgonggrijp** [comment]
Reading this again, I have an idea regarding your first post. Would `pip-compile --upgrade --dry-run` suit your needs?

Regarding your second post, I'm a bit confused. If there is no new version, surely the dependency is not outdated? I'm probably misunderstanding what you wrote, so please clarify.

**Comment by jgonggrijp** [comment]
I'm closing this for lack of evidence that there is an actual issue. Please add a new comment if you feel this issue should be reopened.
