### ISSUE TITLE
[interactive] show all update prior to ask for all

### ISSUE THREAD

**Issue by sylvain-bougnoux** [jgonggrijp/pip-review#72]
`pip-review -i` shows the 1st update and ask for `yes, no, all, quit`. It would be convenient to show all possible updates prior to pressing 'A', because sometimes some packages must not be updated. If yes or no, only the 1st one will be treated. I understand I can call `pip list -o` before, but it is a bit long with many packages.

My 2c.

Thanks for this very useful tool anyway.

**Comment by jgonggrijp** [comment]
Thank you for taking the effort to give feedback.

I'm not sure I understand the issue. You would like to see all the possible updates, but you find `pip list -o` a bit long. Surely, you expect to see the same list of possible updates from pip-review? In fact, this is almost exactly what you get to see when you run `pip-review` (without the `-i` or `-a` flag).

**Comment by jgonggrijp** [comment]
Thanks for the explanation. Pull requests and more opinions welcome.

**Comment by jgonggrijp** [comment]
@sylvain-bougnoux I suddenly wondered. Doesn't `pip-review` followed by `pip-review -a`approximately do what you describe?

**Comment by sylvain-bougnoux** [comment]
Actually yes. The only issue is that you have to wait twice for pip-review to know what to do. One pip-review call takes for me about 20-30s to respond. It is awkward to have to wait twice.
Thanks

**Comment by jgonggrijp** [comment]
Ah, you mentioned the having to wait twice before. Sorry for overlooking that in my previous comment. I find the use case very reasonable.

How about the following. Add a `--batch` option which, when used together with `--interactive` (together `-ib` in short), will cause all available updates to show immediately, followed by a single question: `install all updates? (y/n)`.

Please don't wait for me to implement it, though. See #76. I'll welcome a pull request that implements something like this.

**Comment by kunif** [comment]
This is a feature I want even in `--auto` mode.
It would be nice if the list was displayed before the actual update work was called.

It has less information and less real-time than the progress bar discussed in issue #77, but it seems easy to implement.

And being presented with a list of what will be updated in advance gives you a sense of security that you are aware of the situation in either mode.

If someone responds to this for both modes, would the option name be around `--preview`?

**Comment by jgonggrijp** [comment]
Implemented by @kunif in #91.
