### ISSUE TITLE
Show overall results and errors

### ISSUE THREAD

**Issue by baterflyrity** [jgonggrijp/pip-review#78]
Hi.
How can I see overall results including errors? Something like this:

> Successfully updated 57/60 packages.
> Could not update 3 packages: tensorflow, radon, gitsome.

**Comment by jgonggrijp** [comment]
@baterflyrity `pip-review` just makes a selection of packages to update and then hands everything to `pip install`, including the decision of what to print to `stdout`. If you want a final tally after installation, please submit a feature request to https://github.com/pypa/pip.
