### ISSUE TITLE
Tryes to update pinned requirements

### ISSUE THREAD

**Issue by baterflyrity** [jgonggrijp/pip-review#79]
Hi.
Reading change logs I found some points on that pip-review do not updates packages that are required by others. But it actually fails to handle this update case.

> pip-review -a
> ERROR: tensorflow 2.0.0 has requirement gast==0.2.2, but you'll have gast 0.3.3 which is incompatible.

Also tensorflow works with errors/warnings.  So then i need to manually do something with this package.

> tensorflow==2.0.0
> gast==0.2.2
> pip install tensorflow -U
> tensorflow==2.2.0rc2
> gast==0.3.3

I'm not sure how and where (guess in pip install) it fails but it does.

**Comment by jgonggrijp** [comment]
@baterflyrity `pip-review` is a very simple tool that takes no dependencies into account and that simply updates everything to the latest version no matter what. This is a known limitation that the original creator solved by dropping `pip-review` altogether and replacing it by more sophisticated tools called `pip-compile` and `pip-sync`. These are part of the `pip-tools` package (which `pip-review` used to be a part of) and I recommend  that you use that instead.

The current `pip-review` is just a continuation of the old tool for those who liked their old workflow and don't need the added sophistication. But I think you do need that sophistication and the new `pip-tools` has you covered.

**Comment by baterflyrity** [comment]
@jgonggrijp Thanks for forwarding. I had been really think that tools are discontinued before you replied.
