### ISSUE TITLE
"pip-review -a" updates an package to newest version while the older version is required by other package.

### ISSUE THREAD

**Issue by qycaitian** [jgonggrijp/pip-review#84]
Got this error while running "pip-review -a":
ERROR: astroid 2.4.2 has requirement lazy-object-proxy==1.4.*, but you'll have lazy-object-proxy 1.5.0 which is incompatible.
And it still updated lazy-object-proxy to 1.5.0, which broke the dependency of astroid.

Can pip-review check the dependency first before updating?

**Comment by jgonggrijp** [comment]
Unfortunately, it can't. pip-review is just a dumb updater. To have this kind of functionality, you can use the modern [pip-tools](https://github.com/jazzband/pip-tools) instead. `pip-compile -U` will recompile your `requirements.txt` such that package versions are updated in a non-breaking way. If you subsequently run `pip-sync`, the newer versions in the updated `requirements.txt` will be installed and any obsolete packages will be removed.

Closing, but please feel free to comment if you have further questions.
