### ISSUE TITLE
Constraints.txt is not working or I cannot figure out how to make it work

### ISSUE THREAD

**Issue by Asiier** [jgonggrijp/pip-review#85]
Hello,
I tried to set up the constraints file in the other to ignore some packages that won't update correctly and therefore won't let the rest of the packages update successfully.

I have created the constraints.txt file and declare it in both $PIP_CONSTRAINT and ~/.config/pip.config but neither of them will prevent pip-review on trying to update the excluded packages.

`$ ~>  cat ~/.config/pip.conf                                                                 
[global]
constraint = /root/constraints.txt`

`$ ~ > cat ~/constraints.txt                                                                  
distro-info==0.23ubuntu1
gpg==1.13.1-unknown
PyGObject==3.36.0`

`$ ~ > $PIP_CONSTRAINT                                                                        
fish: The file '/root/constraints.txt' is not executable by this user`

With all that set up if I try to update via pip-review -a

`! $ ~ > pip-review -a                                                                        
Collecting cryptography==3.4.4
  Using cached cryptography-3.4.4-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
ERROR: Could not find a version that satisfies the requirement distro-info==0.10
ERROR: No matching distribution found for distro-info==0.10`

So I'm not sure If it's not working, or I'm doing something wrong.

P.D.: All the previous was in Ubuntu but in Windows, where or how should I declare the constraints file?

**Comment by jgonggrijp** [comment]
I'll start by saying that I know nothing about `constraints.txt`; I have never used it myself, don't know what it is for (although I can make some inferences based on what you have written), don't know whether `pip-review` needs to do anything in order to work with it.

However, purely from your comment, I can spot two things that may be worth investigating.

Firstly, your `pip.conf` and your `$PIP_CONSTRAINT` both point to `/root/constraints.txt`, but the constraints file you dumped the contents of is at `~/constraints.txt`. That's not the same. `~` is a shorthand for something like `/home/Asiier` (depending on your OS and your actual username).

Secondly, will you get the same error if you leave `pip-review` out of the equation, i.e., if you run `pip install -U cryptography` directly?

I also don't know anything about Windows.

**Comment by Asiier** [comment]
I though the constraints file was part of pip-review and not pip itself.
I did some more digging on the documentation and seems we both got some things wrong.

First of all, the config files is independent for each user, so If you are going to execute pip-review as root you will need a config file on the root directory. The constraints file can be the same for both as long as is readable for said users.
Secondly, the config file must be on ~/.config/pip/pip.conf and not ~/.config/pip.conf. So If you could change that on the documentation would be great.

With this 2 changes when I manually try to upgrade the packages using I get the following message.
``` $ ~/.config > pip install -U distro-info                                                 
Requirement already satisfied: distro-info in /usr/lib/python3/dist-packages (0.23ubuntu1)```

Which means it works great!
But when I try the auto mode on pip-review, it doesn't seem to catch the exclusion and I get this:
```
 $ ~/.config > pip-review -a                                                              
Collecting cryptography==3.4.4
  Using cached cryptography-3.4.4-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
ERROR: Could not find a version that satisfies the requirement distro-info==0.10
ERROR: No matching distribution found for distro-info==0.10
```

Looking at the documentation I also found that you can specify the constraints file with "-c". So maybe that could be implemented in the code, so it checks for that file and force pip to exclude the declared packages.
https://pip.pypa.io/en/stable/user_guide/#constraints-files

But seems like pip will still show the package as outdated even If it's declared in the constraints file, so pip-review will try to upgrade it anyways.
I guess you could manually check for the file and exclude the packages inside it.

**Comment by jgonggrijp** [comment]
Thanks for that documentation link. Now I finally know what constraints files are about.

You ran `pip install -U distro-info`. What happens if you run `pip install -U cryptography`?

You can already pass the `-c` option to `pip-review`. It forwards all options it doesn't recognize to `pip`.

**Comment by Asiier** [comment]
Cryptography updates correctly, it's all showing just because it happens to be the first package I have installed and the second is distro-info, which is the one that gives the error and I want to exclude. But here is the output:
```
root@XPS:~# pip install -U cryptography
Requirement already satisfied: cryptography in /usr/local/lib/python3.8/dist-packages (3.4.4)
/usr/local/lib/python3.8/dist-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/local/lib/python3.8/dist-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography) (1.14.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography) (2.20)
```

Yeah, the problem is that you check the packages with `pip list --outdated` and that command would not take the `-c` option. And then, with the output from that command it creates the list of packages to update. The problem is that If you specify the version of the package on the command it will ignore the constraints file even If specify. 
So If you do `pip install -U distro-info` or `pip install -U distro-info -c /root/constrains.txt` it won't try to update the package as long as the package is excluded in the file. But If you do `pip install -U distro-info==0.10 -c /root/constrains.txt`, it will try updating anyways.

I guess you could modify the code, so you only pass the package name and not the version and let pip handle the version to update.

I hope I have explained my self.

**Comment by Asiier** [comment]
I modified the code and by changing `'{0}=={1}'.format(pkg['name'], pkg['latest_version']` to `'{0}'.format(pkg['name']` and then passing the `-U` argument it works perfectly.
It uses the exclusions from the constraints.txt file and upgrade the rest of the packages.

**Comment by jgonggrijp** [comment]
Sounds like you fixed a bug. Please submit a PR!

**Comment by Asiier** [comment]
Okay, I have created the pull request with the changed.
I also added the `-U` by default, so it's not necessary to include it as an argument.
Feel free to change anything of what I added of course.

I'll now close the issue.
