### ISSUE TITLE
update latest version on pypi.org

### ISSUE THREAD

**Issue by Mark-Joy** [jgonggrijp/pip-review#87]
Hi,
Could you please update latest pip-review on pypi.org?
https://pypi.org/project/pip-review/

**Comment by jgonggrijp** [comment]
@Mark-Joy Please clarify what you mean by your request.

**Comment by Mark-Joy** [comment]
@jgonggrijp Hi, when I do `pip install pip-review`, I did not get the latest version. The date on [pipy](https://pypi.org/project/pip-review/) was `Mar 22, 2020`
There was some updates at github such as: constraint file and other fixes..

**Comment by jgonggrijp** [comment]
I see. I'll try to get to it on Friday.

**Comment by Mark-Joy** [comment]
@jgonggrijp how was the update going on?

**Comment by jgonggrijp** [comment]
Terribly sorry, I forgot about it and I didn't roll the update. My next opportunity is Wednesday, November 17. I'll write it down it in my agenda.

**Comment by Mark-Joy** [comment]
@jgonggrijp Since today is Nov-17, a reminder here may help a little bit :)

**Comment by jgonggrijp** [comment]
@Mark-Joy Version 1.1.1 is now up on PyPI. Sorry for the long delay. Merry christmas!
