### ISSUE TITLE
add --ignore-failed

### ISSUE THREAD

**Issue by PyCoding-A** [jgonggrijp/pip-review#88]
I think we should add the feature to ignore failed install because sometimes some packages (especially on TrueNas) are capricious to update ...
if we run a cron job it's better to have the option --ignore-failed next to -auto

**Comment by jgonggrijp** [comment]
I won't be implementing this, but pull requests are welcome. Thumbs-up and thumbs-down to express your opinion about the proposed feature also welcome.
