### ISSUE TITLE
pip-review does not upgrade pip?

### ISSUE THREAD

**Issue by xoviat** [jgonggrijp/pip-review#9]
Pip gave me messages that it was out of date and continued after running `pip-review --auto`. Pip was updated after running `pip install -U pip`.

**Comment by jgonggrijp** [comment]
Do you consider this a bug? I'm not sure whether pip-review should upgrade pip, or pip should be the only program doing that. If I'm right, the current pip-tools don't update pip, either.

**Comment by xoviat** [comment]
Is pip the only package not automatically upgraded? If so, I will close this.

**Comment by jgonggrijp** [comment]
As far as I know, pip is the only package not being updated by pip-review. But please don't take my word for it and do some testing to confirm. :-)

**Comment by jgonggrijp** [comment]
From #13 it appears that pip-review does not update `setuptools`, either. I did not find an exception list in the source code, so both omissions are mysterious. Pull requests are welcome.

**Comment by xoviat** [comment]
The reason for the omission is that neither setuptools nor pip are listed in the `pip freeze` command. What I will probably do is run `pip list --outdated` and then cross check the results with `pip freeze` in order to ensure that no packages are omitted. However, that method would require an explicit exemption for pip unless we want to have `python -m pip` logic.

**Comment by xoviat** [comment]
I should say that I would personally favor upgrading pip as well. Would it be acceptable to put the `python -m pip` logic in?

**Comment by jgonggrijp** [comment]
I don't know. What do you mean by "the `python -m pip` logic"? Does pip behave differently when invoked as a module? Are you talking about actually borrowing logic from pip, or just about taking a particular approach?

**Comment by xoviat** [comment]
When pip upgrades itself, [the documentation recommends](https://pip.pypa.io/en/stable/installing/#upgrading-pip) that instead of executing `pip install --upgrade pip`, the command `python -m pip install --upgrade pip` should be executed because pip is overwriting its own files. The logic that I am suggesting is that if and only if pip is being upgraded, it should be run in module mode, otherwise, pip should be run directly.

**Comment by jgonggrijp** [comment]
If you mean "make a special case for upgrading pip in the code, where pip itself is upgraded using `python -m pip` instead of just `pip`", I'm totally fine with that.
