### ISSUE TITLE
About options that can be passed to the pip list command

### ISSUE THREAD

**Issue by kunif** [jgonggrijp/pip-review#90]
A variable called "LIST_ONLY" defines a set of options that can be passed to the pip list command.
However, even though there is "exclude-editable" in it, there is no "exclude".
Is there any reason for that?
This is just a question.

**Comment by jgonggrijp** [comment]
An option is in there *only* if both of the following conditions apply:

- it is accepted by `pip list`;
- it is *not* accepted by `pip install`.

If both conditions apply and it isn't in there, that might be because the option was introduced after we first created that constant?

**Comment by kunif** [comment]
Oh, I understand.
Looking at it, I found a description in pip's changelog that it was added from v20.3b1(2020-10-31).
Thank you.
