### ISSUE TITLE
Are old versions saved somewhere?

### ISSUE THREAD

**Issue by muslu** [jgonggrijp/pip-review#96]
Hi,
Thanks for this good project.

If i want to downgrade than can i?

**Comment by jgonggrijp** [comment]
Hi @muslu, yes you can downgrade any package in general with the following command:

```sh
pip install -U PACKAGE==x.y.z
```

with `PACKAGE` the name of the package (for example `pip-review`) and `x.y.z` the version you want to downgrade to (for example 0.5.0).

Which package would you like to downgrade, and why?

**Comment by muslu** [comment]
Hi @jgonggrijp thanks for answer.

Yes, we can use -U argument with pip but i want to save version before upgrade. For example i upgraded fastapi but i didnt know old version number then if i need to downgrade with old version, i need to try downgrade one by one.

I think I could tell you.

**Comment by jgonggrijp** [comment]
To see exactly which versions you have installed of each package, you can run `pip list`. Also a common trick is to run `pip freeze >requirements.txt`, so you store all those versions in a file and you can return to those versions later. Better yet is to install `pip-tools`, list your direct dependencies in a `requirements.in`, and then run `pip-compile` to create a `requirements.txt` with all packages and their dependencies pinned to versions that are compatible with each other. `pip-sync` will then install exactly those versions and also uninstall packages that aren't listed.

Commit your `requirements.txt` (and your `requirements.in` if you have one) to VCS, so you can always return to the set of package versions that worked with a given version of your code.

**Comment by muslu** [comment]
Thanks @jgonggrijp;

freeze is good method and useable. 

I wanted to give information to help you; may you want to add to question ("do you want to save old versions of libs?") to command line.

I am closing this ask.

thanks for your time.
